Repository SWE-team11/tetris, pull requests merged in 2022-04, with the labels that each got.

#24 Feat: 블럭 한번에 내리기, 블럭 쌓이기 기능
  src/team11/tetris/Tetris.java
  src/team11/tetris/blocks/Block.java
  src/team11/tetris/blocks/IBlock.java
  src/team11/tetris/blocks/JBlock.java
  src/team11/tetris/blocks/LBlock.java
  src/team11/tetris/blocks/OBlock.java
  src/team11/tetris/blocks/SBlock.java
  src/team11/tetris/blocks/TBlock.java
  src/team11/tetris/blocks/ZBlock.java
  src/team11/tetris/model/BoardModel.java
  src/team11/tetris/presenter/BoardPresenter.java
  src/team11/tetris/view/BoardView.java
Labels: 🔥 Feat

#25 Feat: 블럭 한줄로 쌓이면 지우는 기능 추가 #16
  src/team11/tetris/model/BoardModel.java
  src/team11/tetris/presenter/BoardPresenter.java
Labels: 🔥 Feat

#29 Refactor: 블럭 움직이기 리팩터링
  src/team11/tetris/model/BoardModel.java
Labels: 🛠 Refactor

#30 Feat: 블럭 회전 기능 추가
  src/team11/tetris/blocks/Block.java
  src/team11/tetris/model/BoardModel.java
  src/team11/tetris/presenter/BoardPresenter.java
  src/team11/tetris/view/BoardView.java
Labels: 🔥 Feat

#35 Refactor: Board -> Game 리네이밍 #34
  app/src/main/java/tetris/App.java
  app/src/main/java/tetris/model/GameModel.java
  app/src/main/java/tetris/presenter/BoardPresenter.java
  app/src/main/java/tetris/presenter/GamePresenter.java
  app/src/main/java/tetris/view/GameView.java
Labels: 🛠 Refactor

#37 Feat: 여러 뷰 관리 및 이동 기능 추가 #20
  app/src/main/java/tetris/App.java
  app/src/main/java/tetris/presenter/GamePresenter.java
  app/src/main/java/tetris/presenter/MainPresenter.java
  app/src/main/java/tetris/utills/Presenter.java
  app/src/main/java/tetris/view/MainView.java
Labels: 🔥 Feat

#40 Refactor: GameModel, Block #39 리펙토링
  app/src/main/java/tetris/blocks/Block.java
  app/src/main/java/tetris/blocks/IBlock.java
  app/src/main/java/tetris/blocks/JBlock.java
  app/src/main/java/tetris/blocks/LBlock.java
  app/src/main/java/tetris/blocks/OBlock.java
  app/src/main/java/tetris/blocks/SBlock.java
  app/src/main/java/tetris/blocks/TBlock.java
  app/src/main/java/tetris/blocks/ZBlock.java
  app/src/main/java/tetris/model/GameModel.java
  app/src/main/java/tetris/utils/BlockKind.java
  app/src/main/java/tetris/utils/BoardElement.java
  app/src/main/java/tetris/view/GameView.java
  config/checkstyle.xml
Labels: 🛠 Refactor

#41 Feat: RecordModel 작성 #11
  app/src/main/java/tetris/model/RecordModel.java
Labels: 🛠 Refactor

#38 Feat: ConfigModel 작성 #9 #27
  app/src/main/java/tetris/App.java
  app/src/main/java/tetris/model/ConfigModel.java
  app/src/main/java/tetris/model/GameModel.java
  app/src/main/java/tetris/presenter/GamePresenter.java
  app/src/main/java/tetris/utils/BoardElement.java
  app/src/main/java/tetris/view/GameView.java
  config/checkstyle.xml
Labels: 🔥 Feat

#42 Feat: 블럭 생성 위치에 이미 블럭이 있으면 게임종료#17
  app/src/main/java/tetris/App.java
  app/src/main/java/tetris/model/ConfigModel.java
  app/src/main/java/tetris/model/GameModel.java
  app/src/main/java/tetris/presenter/GamePresenter.java
  app/src/main/java/tetris/view/GameView.java
Labels: 🔥 Feat

#45 Fix: 게임 조작 안되는 문제 #44
  app/src/main/java/tetris/App.java
  app/src/main/java/tetris/presenter/GamePresenter.java
  app/src/main/java/tetris/presenter/MainPresenter.java
  app/src/main/java/tetris/utils/Presenter.java
  app/src/main/java/tetris/view/MainView.java
  config/checkstyle.xml
Labels: 🐛 Fix

#47 Feat: 환경설정, 기록 저장 및 로드 기능 #12
  .gitignore
  app/src/main/java/tetris/App.java
  app/src/main/java/tetris/model/ConfigModel.java
  app/src/main/java/tetris/model/RecordModel.java
  app/src/main/java/tetris/presenter/GamePresenter.java
  app/src/main/java/tetris/presenter/MainPresenter.java
Labels: 🐛 Fix

#57 Feat: 한줄 삭제 이펙트 구현
  app/src/main/java/tetris/model/ConfigModel.java
  app/src/main/java/tetris/model/GameModel.java
  app/src/main/java/tetris/presenter/GamePresenter.java
Labels: 🔥 Feat

#58 Feat: 라인 클리어 아이템 구현
  app/src/main/java/tetris/App.java
  app/src/main/java/tetris/blocks/IBlock.java
  app/src/main/java/tetris/blocks/JBlock.java
  app/src/main/java/tetris/blocks/LBlock.java
  app/src/main/java/tetris/blocks/OBlock.java
  app/src/main/java/tetris/blocks/SBlock.java
  app/src/main/java/tetris/blocks/TBlock.java
  app/src/main/java/tetris/blocks/ZBlock.java
  app/src/main/java/tetris/items/LineClearItem.java
  app/src/main/java/tetris/model/ConfigModel.java
  app/src/main/java/tetris/model/GameModel.java
  app/src/main/java/tetris/presenter/GamePresenter.java
  app/src/main/java/tetris/utils/Block.java
  app/src/main/java/tetris/utils/BlockKind.java
  app/src/main/java/tetris/utils/BoardElement.java
Labels: 🔥 Feat

#66 Feat: Down될 때 마다 점수 추가 #14
  app/src/main/java/tetris/model/GameModel.java
Labels: 🔥 Feat

#64 Feat: 기록에 이름 데이터 추가
  app/src/main/java/tetris/model/RecordModel.java
Labels: 🔥 Feat

#70 Feat: 게임 스피드 증가 기능
  app/src/main/java/tetris/model/GameModel.java
  app/src/main/java/tetris/presenter/GamePresenter.java
Labels: 🔥 Feat

#68 Feat: GameModel 다음 블럭 미리 생성 기능
  app/src/main/java/tetris/model/GameModel.java
Labels: 🔥 Feat

#69 Feat: 난이도에 따른 GameModel 블럭 생성
  app/src/main/java/tetris/model/ConfigModel.java
  app/src/main/java/tetris/model/GameModel.java
  app/src/main/java/tetris/utils/BlockKind.java
Labels: 🔥 Feat

#72 Feat: 메인 뷰 버튼 기능 구현 구현 #51
  app/src/main/java/tetris/App.java
  app/src/main/java/tetris/model/ConfigModel.java
  app/src/main/java/tetris/model/GameModel.java
  app/src/main/java/tetris/model/RecordModel.java
  app/src/main/java/tetris/presenter/ConfigPresenter.java
  app/src/main/java/tetris/presenter/GamePresenter.java
  app/src/main/java/tetris/presenter/MainPresenter.java
  app/src/main/java/tetris/view/ConfigView.java
  app/src/main/java/tetris/view/GameView.java
  app/src/main/java/tetris/view/MainView.java
Labels: 🔥 Feat

#74 Feat: Bomb, Perfect Clear 아이템 구현
  app/src/main/java/tetris/items/BombItem.java
  app/src/main/java/tetris/items/CrossDeleteItem.java
  app/src/main/java/tetris/model/GameModel.java
  app/src/main/java/tetris/utils/Block.java
  app/src/main/java/tetris/utils/BlockKind.java
  app/src/main/java/tetris/utils/BoardElement.java
Labels: 🔥 Feat

#75 Feat: GameView 기능 적용
  app/src/main/java/tetris/model/GameModel.java
  app/src/main/java/tetris/presenter/GamePresenter.java
  app/src/main/java/tetris/view/GameView.java
Labels: 🔥 Feat

#81 Feat: launch4j 적용 및 .exe 생성
  app/bin/main/icon/icon.ico
  app/bin/main/image/GameViewBackground.png
  app/bin/main/tetris/App$View.class
  app/bin/main/tetris/App.class
  app/bin/main/tetris/blocks/Block.class
  app/bin/main/tetris/blocks/IBlock.class
  app/bin/main/tetris/blocks/JBlock.class
  app/bin/main/tetris/blocks/LBlock.class
  app/bin/main/tetris/blocks/OBlock.class
  app/bin/main/tetris/blocks/SBlock.class
  app/bin/main/tetris/blocks/TBlock.class
  app/bin/main/tetris/blocks/ZBlock.class
  app/bin/main/tetris/items/BombItem.class
  app/bin/main/tetris/items/CrossDeleteItem.class
  app/bin/main/tetris/items/LineClearItem.class
  app/bin/main/tetris/items/SameDeleteItem.class
  app/bin/main/tetris/model/ConfigModel$GameDifficulty.class
  app/bin/main/tetris/model/ConfigModel$GameMode.class
  app/bin/main/tetris/model/ConfigModel$PlayerKey.class
  app/bin/main/tetris/model/ConfigModel.class
  app/bin/main/tetris/model/GameModel$Down.class
  app/bin/main/tetris/model/GameModel$GameOver.class
  app/bin/main/tetris/model/GameModel$Left.class
  app/bin/main/tetris/model/GameModel$Move.class
  app/bin/main/tetris/model/GameModel$Result.class
  app/bin/main/tetris/model/GameModel$Right.class
  app/bin/main/tetris/model/GameModel$Rotate.class
  app/bin/main/tetris/model/GameModel.class
  app/bin/main/tetris/model/RecordModel$Record.class
  app/bin/main/tetris/model/RecordModel.class
  app/bin/main/tetris/presenter/ConfigPresenter.class
  app/bin/main/tetris/presenter/GamePresenter$DeleteTimerActionListener.class
  app/bin/main/tetris/presenter/GamePresenter$MainTimerActionListener.class
  app/bin/main/tetris/presenter/GamePresenter$TimerActionListener.class
  app/bin/main/tetris/presenter/GamePresenter.class
  app/bin/main/tetris/presenter/MainPresenter.class
  app/bin/main/tetris/utills/Presenter.class
  app/bin/main/tetris/utils/Block.class
  app/bin/main/tetris/utils/BlockKind.class
  app/bin/main/tetris/utils/BoardElement.class
  app/bin/main/tetris/utils/Presenter.class
  app/bin/main/tetris/view/ConfigView.class
  app/bin/main/tetris/view/GameView$1.class
  app/bin/main/tetris/view/GameView$PauseKeyListener.class
  app/bin/main/tetris/view/GameView$PlayerKeyListener.class
  app/bin/main/tetris/view/GameView.class
  app/bin/main/tetris/view/MainView$1.class
  app/bin/main/tetris/view/MainView.class
  app/bin/main/tetris/view/MainView2$1.class
  app/bin/main/tetris/view/MainView2.class
  app/build.gradle
  app/src/main/resources/icon/icon.ico
Labels: 🔥 Feat

#82 Feat: 환경설정 뷰 작성 #10
  app/src/main/java/tetris/view/ConfigView.java
  app/src/main/resources/image/configBackground.png
Labels: 🔥 Feat

#84 Refactor: 게임 화면 이미지 분리 #80
  app/src/main/java/tetris/view/GameView.java
  app/src/main/resources/image/GameViewBackground.png
  app/src/main/resources/image/level.png
  app/src/main/resources/image/lines.png
  app/src/main/resources/image/next.png
  app/src/main/resources/image/score.png
Labels: 🔥 Feat

#89 Feat: 무게추 아이템 구현
  app/bin/main/image/GameViewBackground.png
  app/bin/main/image/configBackground.png
  app/bin/main/image/level.png
  app/bin/main/image/lines.png
  app/bin/main/image/next.png
  app/bin/main/image/score.png
  app/bin/main/image/smallExit.png
  app/bin/main/tetris/items/WeightItem.class
  app/bin/main/tetris/model/ConfigModel$GameDifficulty.class
  app/bin/main/tetris/model/ConfigModel$GameMode.class
  app/bin/main/tetris/model/ConfigModel$PlayerKey.class
  app/bin/main/tetris/model/ConfigModel.class
  app/bin/main/tetris/model/GameModel$Down.class
  app/bin/main/tetris/model/GameModel$GameOver.class
  app/bin/main/tetris/model/GameModel$Left.class
  app/bin/main/tetris/model/GameModel$Move.class
  app/bin/main/tetris/model/GameModel$Right.class
  app/bin/main/tetris/model/GameModel$Rotate.class
  app/bin/main/tetris/model/GameModel.class
  app/bin/main/tetris/model/RecordModel$Record.class
  app/bin/main/tetris/model/RecordModel.class
  app/bin/main/tetris/presenter/GamePresenter$DeleteTimerActionListener.class
  app/bin/main/tetris/presenter/GamePresenter$MainTimerActionListener.class
  app/bin/main/tetris/presenter/GamePresenter$WeightItemTimerActionListener.class
  app/bin/main/tetris/presenter/GamePresenter.class
  app/bin/main/tetris/utils/BlockKind.class
  app/bin/main/tetris/utils/BoardElement.class
  app/bin/main/tetris/view/ConfigView$1.class
  app/bin/main/tetris/view/ConfigView.class
  app/bin/main/tetris/view/GameView$1.class
  app/bin/main/tetris/view/GameView$2.class
  app/bin/main/tetris/view/GameView$3.class
  app/bin/main/tetris/view/GameView$4.class
  app/bin/main/tetris/view/GameView$5.class
  app/bin/main/tetris/view/GameView$PauseKeyListener.class
  app/bin/main/tetris/view/GameView$PlayerKeyListener.class
  app/bin/main/tetris/view/GameView.class
  app/src/main/java/tetris/items/WeightItem.java
  app/src/main/java/tetris/model/ConfigModel.java
  app/src/main/java/tetris/model/GameModel.java
  app/src/main/java/tetris/model/RecordModel.java
  app/src/main/java/tetris/presenter/GamePresenter.java
  app/src/main/java/tetris/utils/BlockKind.java
  app/src/main/java/tetris/utils/BoardElement.java
Labels: 🔥 Feat

#90 Feat: 환경설정 기능 완료 #26
  app/src/main/java/tetris/model/ConfigModel.java
  app/src/main/java/tetris/model/RecordModel.java
  app/src/main/java/tetris/presenter/GamePresenter.java
  app/src/main/java/tetris/view/ConfigView.java
  app/src/main/java/tetris/view/GameView.java
Labels: 🔥 Feat

#91 Feat: 스코어 입력 다이얼로그 개발 #62
  app/src/main/java/tetris/presenter/GamePresenter.java
  app/src/main/java/tetris/view/GameView.java
  app/src/main/resources/image/enter.png
  app/src/main/resources/image/scoreDialog.png
Labels: 🔥 Feat

#93 Feat: 기록 저장 기능 구현 #76
  app/src/main/java/tetris/presenter/GamePresenter.java
  app/src/main/java/tetris/view/GameView.java
Labels: 🔥 Feat

#92 Feat: 스코어보드 뷰 개발 #63
  app/bin/main/image/continue.png
  app/bin/main/image/pausePanel.png
  app/bin/main/image/scoreBoard.png
  app/bin/main/image/toMain.png
  app/bin/main/image/toRecord.png
  app/src/main/java/tetris/App.java
  app/src/main/java/tetris/model/RecordModel.java
  app/src/main/java/tetris/presenter/RecordPresenter.java
  app/src/main/java/tetris/utils/Record.java
  app/src/main/java/tetris/view/MainView.java
  app/src/main/java/tetris/view/RecordView.java
  app/src/main/resources/image/scoreBoard.png
  app/src/main/resources/image/toRecord.png
Labels: 🔥 Feat

#95 Feat: 난이도 선택 기능
  app/src/main/java/tetris/model/ConfigModel.java
  app/src/main/java/tetris/view/MainView.java
  app/src/main/resources/image/easyLevel.png
  app/src/main/resources/image/easyLevelClicked.png
  app/src/main/resources/image/hardLevel.png
  app/src/main/resources/image/hardLevelClicked.png
  app/src/main/resources/image/normalLevel.png
  app/src/main/resources/image/normalLevelClicked.png
Labels: 🔥 Feat

#96 Feat: 스코어보드 구현 #77
  app/src/main/java/tetris/model/RecordModel.java
  app/src/main/java/tetris/presenter/GamePresenter.java
  app/src/main/java/tetris/presenter/RecordPresenter.java
  app/src/main/java/tetris/utils/Record.java
  app/src/main/java/tetris/view/GameView.java
  app/src/main/java/tetris/view/RecordView.java
Labels: 🔥 Feat

#97 Fix: 윈도우 스타일 수정 #77
  app/src/main/java/tetris/view/RecordView.java
Labels: 🐛 Fix
